-- CreateTable
CREATE TABLE "USER" (
    "User_ID" SERIAL NOT NULL,
    "Username" VARCHAR(255) NOT NULL,
    "Email" VARCHAR(255) NOT NULL,
    "Password_Hash" VARCHAR(255) NOT NULL,
    "Registration_Date" DATE NOT NULL,
    "Is_Verified" BOOLEAN NOT NULL,
    "Current_Role_ID" INTEGER NOT NULL,
    "Tier_ID" INTEGER NOT NULL,

    CONSTRAINT "USER_pkey" PRIMARY KEY ("User_ID")
);

-- CreateTable
CREATE TABLE "ROLE" (
    "Role_ID" SERIAL NOT NULL,
    "Role_Name" VARCHAR(255) NOT NULL,

    CONSTRAINT "ROLE_pkey" PRIMARY KEY ("Role_ID")
);

-- CreateTable
CREATE TABLE "SUBSCRIPTION_TIER" (
    "Tier_ID" SERIAL NOT NULL,
    "Tier_Name" VARCHAR(255) NOT NULL,
    "Daily_Download_Limit" INTEGER NOT NULL,
    "Daily_Citation_Limit" INTEGER NOT NULL,
    "Max_Bookmarks" INTEGER NOT NULL,
    "Has_Ads" BOOLEAN NOT NULL,
    "Has_AI_Insights" BOOLEAN NOT NULL,

    CONSTRAINT "SUBSCRIPTION_TIER_pkey" PRIMARY KEY ("Tier_ID")
);

-- CreateTable
CREATE TABLE "DOCUMENT" (
    "Document_ID" SERIAL NOT NULL,
    "Title" VARCHAR(255) NOT NULL,
    "Abstract" TEXT NOT NULL,
    "File_Path" VARCHAR(255) NOT NULL,
    "Date_Published" DATE NOT NULL,
    "Visibility" VARCHAR(50) NOT NULL,
    "Downloads_Count" INTEGER NOT NULL DEFAULT 0,
    "Citation_Count" INTEGER NOT NULL DEFAULT 0,
    "AI_Summary" TEXT,
    "AI_Insights" TEXT,
    "Uploader_ID" INTEGER NOT NULL,
    "Course_ID" INTEGER NOT NULL,
    "ResourceType_ID" INTEGER NOT NULL,
    "Library_ID" INTEGER NOT NULL,

    CONSTRAINT "DOCUMENT_pkey" PRIMARY KEY ("Document_ID")
);

-- CreateTable
CREATE TABLE "USER_BOOKMARK" (
    "User_ID" INTEGER NOT NULL,
    "Document_ID" INTEGER NOT NULL,
    "Date_Bookmarked" DATE NOT NULL,

    CONSTRAINT "USER_BOOKMARK_pkey" PRIMARY KEY ("User_ID","Document_ID")
);

-- CreateTable
CREATE TABLE "DOCUMENT_AUTHOR" (
    "Document_ID" INTEGER NOT NULL,
    "Author_ID" INTEGER NOT NULL,
    "Author_Order" INTEGER NOT NULL,

    CONSTRAINT "DOCUMENT_AUTHOR_pkey" PRIMARY KEY ("Document_ID","Author_ID")
);

-- CreateTable
CREATE TABLE "AUTHOR" (
    "Author_ID" SERIAL NOT NULL,
    "Full_Name" VARCHAR(255) NOT NULL,
    "Email" VARCHAR(255) NOT NULL,

    CONSTRAINT "AUTHOR_pkey" PRIMARY KEY ("Author_ID")
);

-- CreateTable
CREATE TABLE "DOCUMENT_KEYWORD" (
    "Document_ID" INTEGER NOT NULL,
    "Keyword_ID" INTEGER NOT NULL,

    CONSTRAINT "DOCUMENT_KEYWORD_pkey" PRIMARY KEY ("Document_ID","Keyword_ID")
);

-- CreateTable
CREATE TABLE "KEYWORD" (
    "Keyword_ID" SERIAL NOT NULL,
    "Keyword_Text" VARCHAR(255) NOT NULL,

    CONSTRAINT "KEYWORD_pkey" PRIMARY KEY ("Keyword_ID")
);

-- CreateTable
CREATE TABLE "COURSE" (
    "Course_ID" SERIAL NOT NULL,
    "Course_Name" VARCHAR(255) NOT NULL,
    "Course_Abbr" VARCHAR(50) NOT NULL,
    "College_ID" INTEGER NOT NULL,

    CONSTRAINT "COURSE_pkey" PRIMARY KEY ("Course_ID")
);

-- CreateTable
CREATE TABLE "COLLEGE" (
    "College_ID" SERIAL NOT NULL,
    "College_Name" VARCHAR(255) NOT NULL,
    "College_Abbr" VARCHAR(50) NOT NULL,

    CONSTRAINT "COLLEGE_pkey" PRIMARY KEY ("College_ID")
);

-- CreateTable
CREATE TABLE "RESOURCE_TYPE" (
    "ResourceType_ID" SERIAL NOT NULL,
    "Type_Name" VARCHAR(255) NOT NULL,

    CONSTRAINT "RESOURCE_TYPE_pkey" PRIMARY KEY ("ResourceType_ID")
);

-- CreateTable
CREATE TABLE "LIBRARY" (
    "Library_ID" SERIAL NOT NULL,
    "Name" VARCHAR(255) NOT NULL,

    CONSTRAINT "LIBRARY_pkey" PRIMARY KEY ("Library_ID")
);

-- CreateTable
CREATE TABLE "ACTIVITY_LOG" (
    "Log_ID" BIGSERIAL NOT NULL,
    "User_ID" INTEGER NOT NULL,
    "Document_ID" INTEGER,
    "Activity_Type" VARCHAR(255) NOT NULL,
    "Created_At" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ACTIVITY_LOG_pkey" PRIMARY KEY ("Log_ID")
);

-- CreateIndex
CREATE UNIQUE INDEX "USER_Username_key" ON "USER"("Username");

-- CreateIndex
CREATE UNIQUE INDEX "USER_Email_key" ON "USER"("Email");

-- CreateIndex
CREATE UNIQUE INDEX "KEYWORD_Keyword_Text_key" ON "KEYWORD"("Keyword_Text");

-- AddForeignKey
ALTER TABLE "USER" ADD CONSTRAINT "USER_Current_Role_ID_fkey" FOREIGN KEY ("Current_Role_ID") REFERENCES "ROLE"("Role_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "USER" ADD CONSTRAINT "USER_Tier_ID_fkey" FOREIGN KEY ("Tier_ID") REFERENCES "SUBSCRIPTION_TIER"("Tier_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DOCUMENT" ADD CONSTRAINT "DOCUMENT_Uploader_ID_fkey" FOREIGN KEY ("Uploader_ID") REFERENCES "USER"("User_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DOCUMENT" ADD CONSTRAINT "DOCUMENT_Course_ID_fkey" FOREIGN KEY ("Course_ID") REFERENCES "COURSE"("Course_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DOCUMENT" ADD CONSTRAINT "DOCUMENT_ResourceType_ID_fkey" FOREIGN KEY ("ResourceType_ID") REFERENCES "RESOURCE_TYPE"("ResourceType_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DOCUMENT" ADD CONSTRAINT "DOCUMENT_Library_ID_fkey" FOREIGN KEY ("Library_ID") REFERENCES "LIBRARY"("Library_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "USER_BOOKMARK" ADD CONSTRAINT "USER_BOOKMARK_User_ID_fkey" FOREIGN KEY ("User_ID") REFERENCES "USER"("User_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "USER_BOOKMARK" ADD CONSTRAINT "USER_BOOKMARK_Document_ID_fkey" FOREIGN KEY ("Document_ID") REFERENCES "DOCUMENT"("Document_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DOCUMENT_AUTHOR" ADD CONSTRAINT "DOCUMENT_AUTHOR_Document_ID_fkey" FOREIGN KEY ("Document_ID") REFERENCES "DOCUMENT"("Document_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DOCUMENT_AUTHOR" ADD CONSTRAINT "DOCUMENT_AUTHOR_Author_ID_fkey" FOREIGN KEY ("Author_ID") REFERENCES "AUTHOR"("Author_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DOCUMENT_KEYWORD" ADD CONSTRAINT "DOCUMENT_KEYWORD_Document_ID_fkey" FOREIGN KEY ("Document_ID") REFERENCES "DOCUMENT"("Document_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DOCUMENT_KEYWORD" ADD CONSTRAINT "DOCUMENT_KEYWORD_Keyword_ID_fkey" FOREIGN KEY ("Keyword_ID") REFERENCES "KEYWORD"("Keyword_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "COURSE" ADD CONSTRAINT "COURSE_College_ID_fkey" FOREIGN KEY ("College_ID") REFERENCES "COLLEGE"("College_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ACTIVITY_LOG" ADD CONSTRAINT "ACTIVITY_LOG_User_ID_fkey" FOREIGN KEY ("User_ID") REFERENCES "USER"("User_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ACTIVITY_LOG" ADD CONSTRAINT "ACTIVITY_LOG_Document_ID_fkey" FOREIGN KEY ("Document_ID") REFERENCES "DOCUMENT"("Document_ID") ON DELETE SET NULL ON UPDATE CASCADE;
